
# 1. Nombre de tu gran creación
spring.application.name=riesgocrediticio

# 2. Configuración de H2 (Base de datos en memoria)
spring.datasource.url=jdbc:h2:mem:ordenaris_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# 3. La magia: 'update' crea las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update

# 4. Consola visual (para que entres desde el navegador a ver tus tablas)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# 5. Para que veas en la consola de IntelliJ qué está pasando por debajo
spring.jpa.show-sql=true
spring.jpa.format_sql=true
spring.jpa.open-in-view=false
